# -*- coding: utf-8 -*-
"""Analise_Risco_Credito_Portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12v3fUe9J90pwapPdOEmggrEmWFzFDT9h
"""

# 1. Importação de Bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 2. Simulação de Dados Financeiros (Dados Sintéticos para Exemplo)
# Criando um dataset fictício de 1000 clientes
np.random.seed(42)
n_clientes = 1000
dados = {
    'Idade': np.random.randint(18, 70, n_clientes),
    'Renda_Mensal': np.random.randint(1500, 20000, n_clientes),
    'Divida_Total': np.random.randint(0, 50000, n_clientes),
    'Historico_Pagamento_Ruim': np.random.randint(0, 5, n_clientes), # 0 = nunca atrasou
    'Score_Serasa_Simulado': np.random.randint(300, 1000, n_clientes)
}

df = pd.DataFrame(dados)

# Regra fictícia para definir quem é "Mau Pagador" (Target):
# Se a dívida for alta e o score baixo, chance de default aumenta
df['Inadimplente'] = np.where(
    (df['Divida_Total'] > 10000) & (df['Score_Serasa_Simulado'] < 500), 1, 0
)

# 3. Separação Treino e Teste
X = df.drop('Inadimplente', axis=1) # Variáveis explicativas
y = df['Inadimplente'] # O que queremos prever

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 4. Treinamento do Modelo (Random Forest)
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

# 5. Avaliação do Modelo
predicoes = modelo.predict(X_test)
print("Relatório de Classificação:\n")
print(classification_report(y_test, predicoes))

# 6. Gráfico de Importância das Variáveis (O "Pulo do Gato" Visual)
importancias = modelo.feature_importances_
indices = np.argsort(importancias)[::-1]
variaveis = X.columns

plt.figure(figsize=(10, 6))
plt.title("Quais fatores mais impactam o Risco de Crédito?")
plt.bar(range(X.shape[1]), importancias[indices], align="center", color='#4c72b0')
plt.xticks(range(X.shape[1]), variaveis[indices], rotation=45)
plt.tight_layout()
plt.show() # Isso vai gerar o gráfico na tela